add recency viral load results to HTS data extract Report
METS-Programme/openmrs-module-ugandaemr-reports pull request #327
Opened 2023-03-23 13:58 UTC by Mwanje

2023-03-24 04:47 UTC, ODORA0 requested changes

2023-03-24 04:47 UTC, ODORA0 commented on api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpRecencyHTSClientCardDataExportReport2019.java
> +        dsd.addColumn("recency viral load result", sdd.definition("recencyVLresult", getConcept("dc8d83e3-30ab-102d-86b0-7a5022ba4115")), "onOrAfter=${startDate},onOrBefore=${endDate}", new ObsDataCo
@Mwanje Change `recency viral load result` to `recency_vl_result`

2023-03-24 04:47 UTC, ODORA0 commented on api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpRecencyHTSClientCardDataExportReport2019.java
> +        dsd.addColumn("recency viral load undetectable", sdd.definition("recencyVLundetectable", getConcept("dca1269d-30ab-102d-86b0-7a5022ba4115")), "onOrAfter=${startDate},onOrBefore=${endDate}", n
@Mwanje Change `recency viral load undetectable` to `is_recency_vl_undetectable`

2023-03-30 05:46 UTC, ODORA0 approved these changes

2023-03-31 09:21 UTC, ODORA0 approved these changes

2023-03-31 11:43 UTC, dbaluku approved these changes

2023-03-31 11:45 UTC, solemabrothers approved these changes

2023-04-03 07:53 UTC, merged